version: '3.1'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3307:3306
    volumes:
      - "/Users/yuinakorn/_workspace/Docker/mariadb/data:/var/lib/mysql"
      - "/Users/yuinakorn/_workspace/Docker/mariadb/conf:/etc/mysql/conf.d"
    environment:
      MARIADB_USER: ssj
      MARIADB_PASSWORD: ssj1234
      MYSQL_ROOT_PASSWORD: ssj1234
      MARIADB_INITDB_SKIP_TZINFO: "true"
      TZ: "Asia/Bangkok"

    command: |
      --event-scheduler=ON
      --skip-name-resolve
      --max-connections=1000
      --character-set-server=utf8
      --collation-server=utf8_general_ci

    restart: always
